name: "Dependabot Automerge - Action"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
permissions:
  pull-requests: write
  contents: write
  
jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]' 
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge Dependabot PR
        uses: ridedott/merge-me-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
